### ISSUE TITLE
HTTP error : Too Many Requests (RFC 6585)

### ISSUE THREAD

**Issue by bioshot-dotcom** [umatter/OpenAIR#5]
Hi!

Firstly, thank you for this project! Secondly, I get this error when I try to use this in my RStudio console.
`library(TheOpenAIR)
openai_api_key('my-key')
chat('Hi!')`

HTTP error : Too Many Requests (RFC 6585)
Error in messages(.) :
Invalid parameter value. Expecting list or chatlog object.

I have no clue of what am I doing wrong, thank you!

**Comment by JLDC** [comment]
Hi @bioshot-dotcom 

The message "HTTP error: Too Many Requests" suggests that you have exceeded the rate limit for the OpenAI API. The API has a rate-limiting mechanism to prevent abuse and ensure fair usage for all users. The error message is not due to the package directly and I cannot reproduce this error on any machine and using any API key that I have access to.

Please check the [OpenAI API Rate Limit](https://platform.openai.com/docs/guides/rate-limits) and make sure that your OpenAI API account is not subject to rate-limiting. If multiple people are using this API key, this could also be the root of your problem as the other people might have reached the rate limit.
